# Generated by Django 5.2.17 on 2026-08-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('passing_percentage', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Draft', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='quiz_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
